# Generated by Django 4.2.5 on 2024-01-09 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamer',
            name='gamer_games',
            field=models.CharField(max_length=255),
        ),
    ]
