# Generated by Django 4.2.5 on 2024-01-15 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_alter_games_gamethumbnails_alter_games_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='gameThumbnails',
            field=models.ImageField(help_text='.jpg, .png, .jpeg, .gif, .svg supported', max_length=400, upload_to='thumbnail/', verbose_name='Games Thumbnails'),
        ),
        migrations.AlterField(
            model_name='games',
            name='video',
            field=models.FileField(help_text='.mp4 supported only', max_length=400, upload_to='videos/', verbose_name='Video'),
        ),
    ]
